# Generated by Django 3.0.5 on 2020-12-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=500)),
                ('githubLink', models.TextField()),
                ('liveLink', models.TextField()),
                ('img', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
