# Generated by Django 3.0.5 on 2020-12-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Certificates',
        ),
    ]
